import { StyleSheet, Platform, StatusBar } from "react-native";

export default StyleSheet.create({
  safeContainerTop: {
    flex: 0,
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
  },
  safeContainerBottom: {
    flex: 1,
    alignItems: "center",
  },
  title: {},
  logo: {
    flex: 1,
    height: 59,
    width: 169,
    alignSelf: "center",
    marginHorizontal: 32,
    marginTop: 77,
    marginBottom: 59,
  },
  input: {
    height: 48,
    borderRadius: 5,
    overflow: "hidden",
    backgroundColor: "white",
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 30,
    paddingLeft: 16,
  },
  button: {
    marginLeft: 30,
    marginRight: 30,
    marginTop: 20,
    height: 48,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonTitle: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  footerView: {
    flex: 1,
    alignItems: "center",
    marginTop: 20,
    marginBottom: 20,
  },
  footerText: {
    fontFamily: "Quicksand_500Medium",
    color: "#000000",
    fontStyle: "normal",
    fontSize: 20,
    lineHeight: 24,
    letterSpacing: 0.15,
  },
  row: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 32,
    marginTop: 16,
  },
  rowExtra: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    marginTop: 16,
    paddingRight: 32,
    paddingLeft: 58,
  },
  switchPosition: {
    alignSelf: "flex-start",
  },
  label: {
    flex: 1,
    marginLeft: 10,
    paddingBottom: 8,
    fontFamily: "Quicksand_400Regular",
    fontStyle: "normal",
    lineHeight: 24,
    fontSize: 16,
    letterSpacing: 0.15,
    flexWrap: "wrap",
  },
  footerLink: {
    color: "#2C90CB",
    fontFamily: "Quicksand_700Bold",
    lineHeight: 24,
    letterSpacing: 0.15,
    fontSize: 16,
  },
});
