import { StyleSheet, Platform, StatusBar } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
  },
  safeContainerTop: {
    flex: 0,
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
  },
  safeContainerBottom: {
    flex: 1,
  },
  logo: {
    flex: 1,
    height: 59,
    width: 169,
    alignSelf: "center",
    marginHorizontal: 32,
    marginTop: 77,
    marginBottom: 59,
  },
  input: {
    height: 48,
    borderRadius: 5,
    overflow: "hidden",
    backgroundColor: "white",
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 30,
    paddingLeft: 16,
  },
  button: {
    backgroundColor: "#3239E5",
    marginLeft: 30,
    marginRight: 30,
    marginTop: 20,
    height: 48,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonSecondary: {
    backgroundColor: "#ffa000",
    marginLeft: 30,
    marginRight: 30,
    marginTop: 20,
    height: 48,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonTitleSecondary: {
    color: "black",
    fontSize: 16,
    fontWeight: "bold",
  },
  buttonTitle: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  footerView: {
    flex: 1,
    alignItems: "center",
    marginTop: 20,
  },
  footerText: {
    fontFamily: "Quicksand_500Medium",
    color: "#000000",
    fontStyle: "normal",
    fontSize: 20,
    lineHeight: 24,
    letterSpacing: 0.15,
  },
  footerLink: {
    color: "#ffa000",
    fontWeight: "bold",
    fontSize: 16,
  },
  modalTitle: {
    width: "auto",
    color: "#000000",
    textAlign: "center",
    fontFamily: "Quicksand_500Medium",
    fontStyle: "normal",
    paddingBottom: 8,
    fontSize: 20,
    lineHeight: 24,
    letterSpacing: 0.15,
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.9)",
  },
  buttonRow: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    width: 380,
    justifyContent: "center",
  },
  modalView: {
    margin: 20,
    borderRadius: 20,
    padding: 35,
    height: 330,
    width: 350,
    backgroundColor: "#F1F1F1",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
});
